version: '2'

services:
  php:
    image: "php:${PHP_VERSION}"
    volumes:
      - ./html:/html
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./html:/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
 
